name: "Publish profile: Build and deploy to an Azure Web App"

env:
  # Get from repository variables
  # https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
  BUILD_CSPROJ: './src/openai-loadbalancer.csproj'
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet publish
        run: dotnet publish ${{ env.BUILD_CSPROJ }} -c Release -o ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: dist/${{ env.AZURE_WEBAPP_NAME }}
    

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist/${{ env.AZURE_WEBAPP_NAME }}
